from setuptools import setup

setup(
    name='hadoop_ranger_audit',
    version='0.1',
    packages=['hadoop_ranger_audit'],
    url='https://github.com/jackscodemonkey/hadoop_ranger_audit',
    license='MIT',
    author='Marcus Robb',
    author_email='marcus.robb@initworx.com',
    description='Parses Ranger Policies and matches to Active Directory users',
    install_requires=[
        'alabaster',
        'Babel',
        'certifi',
        'chardet',
        'docutils',
        'idna',
        'imagesize',
        'Jinja2',
        'ldap3',
        'MarkupSafe',
        'packaging',
        'pyasn1',
        'Pygments',
        'pyparsing',
        'pytz',
        'requests',
        'six',
        'snowballstemmer',
        'Sphinx',
        'sphinx-rtd-theme',
        'sphinx-theme',
        'sphinxcontrib-websupport',
        'urllib3'
      ],
    scripts=['hadoop_ranger_audit/hadoop_ranger_audit.py',
             'hadoop_ranger_audit/report_template.html'],
    include_package_data=True,
)
